name: Remote Deploy

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Which service to restart?"
        required: true
        type: choice
        options:
          - nginx
          - db
          - redis
          - all

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            bash /opt/infra/deploy.sh ${{ github.event.inputs.service }}
